cart_grid:
  height: 240
  width: 480
  cell_size: 0.25

pedestrian:
  spawn:
    side:
      min: 0.45
      max: 2.10
    height:
      min: 0.90
      max: 2.25
    semantic:
      min: 0.80
  update:
    side:
      min: 0.25
      max: 2.10
    height:
      min: 0.70
      max: 2.25
    semantic:
      min: 0.50

car:
  spawn:
    side:
      min: 1.10
      max: 5.00
    height:
      min: 0.50
      max: 2.00
    semantic:
      min: 0.80
  update:
    side:
      min: 0.90
      max: 5.00
    height:
      min: 0.50
      max: 2.00
    semantic:
      min: 0.60